spring: 
  datasource: 
    driverClassName: com.mysql.cj.jdbc.Driver 
    url: jdbc:mysql://localhost:3306/cinema_payment_db
    username: root
    password: Infy@123
  jpa: 
    hibernate.ddl-auto: update
    
  application:
    name: PaymentMs
  cloud:
    consul:
      host: localhost
      discovery:
        enabled: true
    
    
server:
  port: 5001